import Head from "next/head";
import ButtonList from "./components/ButtonList.js";

export default function Home() {
  return (
    <div className="bg-slate-200 h-screen">
      <Head>
        <title>carrd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-3xl">
        <div className="flex flex-col justify-center">
          <h1 className="flex justify-center text-3xl font-bold m-4 mt-8 text-slate-900	">
            suzan
          </h1>
          {/* vertical grid starts here */}
          <div className="flex flex-col	justify-items-center gap-2">
            <ButtonList text="about" />
            <ButtonList text="movies" />
            <ButtonList text="shows" />
            <ButtonList text="music" />
          </div>
        </div>
      </main>
    </div>
  );
}
