import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>carrd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-3xl bg-blue-800">
        <div className="flex flex-col justify-center">
          <h1 className="text-3xl font-bold m-4">suzan</h1>
          {/* vertical grid starts here */}
          <div className="grid grid-rows-4">
            <div>01</div>
            <div>02</div>
            <div>03</div>
            <div>09</div>
          </div>
        </div>
      </main>
    </div>
  );
}
